Implemented new Fallback System in Tablist Module
HttxMarco/PoloCloud pull request #10
Opened 2021-08-02 19:51 UTC by iPommes

2021-08-02 22:04 UTC, McMaxDE commented on polocloud-master/src/main/java/de/polocloud/bootstrap/template/fallback/FallbackSearchService.java
>      public List<IGameServer> searchForTemplate(ICloudPlayer cloudPlayer, boolean hubCommand) {
https://hastebin.com/axinujexix.properties

Nullpointer when joining without any MinecraftServer running.

2021-08-02 22:05 UTC, McMaxDE commented on polocloud-master/src/main/java/de/polocloud/bootstrap/network/handler/GameServerRegisterPacketHandler.java
> -            } else {
Not all Server a registered in Bungeecord.

2021-08-02 22:08 UTC, McMaxDE requested changes
Nullpointer when joining without any MinecraftServer running:

https://hastebin.com/axinujexix.properties

Not all MinecraftServer are registered correctly in BungeeCord

2021-08-03 09:56 UTC, iPommes commented on polocloud-master/src/main/java/de/polocloud/bootstrap/template/fallback/FallbackSearchService.java
>      public List<IGameServer> searchForTemplate(ICloudPlayer cloudPlayer, boolean hubCommand) {
Fixed! The error occurred, when the templatename from the fallback server in the config, doesn't exitst

2021-08-03 10:15 UTC, iPommes commented on polocloud-master/src/main/java/de/polocloud/bootstrap/network/handler/GameServerRegisterPacketHandler.java
> -            } else {
Checked everything.
- On my main cloud instance, worked
- Create fresh new cloud instance, worked
- Created new template, worked
- Started new proxy, worked

2021-08-03 16:46 UTC, merged